### ISSUE TITLE
32k words spram with ice40UP5k decoding

### ISSUE THREAD

**Issue by igor-m** [bobbl/danzig#4]
Hi, I tried to add another 16k words of memory (ice40UP5k has got 4 SPRAM blocks). I did it ala picosoc (tried various decoding variants). The pisosoc differs a litlle bit (in using "write" and "wmask"), however. The issue I still see here is following - when reading the sram  it always crashes when crossing the spram_0 to spram_1 boundary. It means the first 16k words decoding works fine, touching the second block (ie reading a value) crashes. Below is the decoding which works fine with 0x00000000 - 0x00003FFF (32bit words) . It could be there is something special I've been still overlooking..

 In up5k.v :
```
..
    SPRAMMemory mainmem (
        .clk    (clk),
        .write  (mem_write_main),
        .wmask  (mem_wmask),
        .wdata  (mem_wdata),
        .addr   (mem_addr[16:2]),                // MOD
        .rdata  (mem_rdata_main)
    );
..

// MOD igor-m 03/2021 - at this moment it works with lower sram block only :(

module SPRAMMemory (
    input clk,
    input write,
    input [3:0] wmask,
    input [31:0] wdata,
    input [14:0] addr,
    output [31:0] rdata
);

	wire cs_0, cs_1;
	wire [31:0] rdata_0, rdata_1;

	assign cs_0  =  addr[14];
	assign cs_1  = !addr[14];
	assign rdata =  cs_0 ? rdata_0 : rdata_1;


SB_SPRAM256KA spram0_lo(
    .DATAIN     (wdata[15:0]),
    .ADDRESS    (addr[13:0]),
    .MASKWREN   ({wmask[1], wmask[1], wmask[0], wmask[0]}),
    .WREN       (write),
    .CHIPSELECT (cs_0),
    .CLOCK      (clk),
    .STANDBY    (1'b0),
    .SLEEP      (1'b0),
    .POWEROFF   (1'b1),
    .DATAOUT    (rdata_0[15:0])
    );

SB_SPRAM256KA spram0_hi(
    .DATAIN     (wdata[31:16]),
    .ADDRESS    (addr[13:0]),
    .MASKWREN   ({wmask[3], wmask[3], wmask[2], wmask[2]}),
    .WREN       (write),
    .CHIPSELECT (cs_0),
    .CLOCK      (clk),
    .STANDBY    (1'b0),
    .SLEEP      (1'b0),
    .POWEROFF   (1'b1),
    .DATAOUT    (rdata_0[31:16])
    );
    
SB_SPRAM256KA spram1_lo(
    .DATAIN     (wdata[15:0]),
    .ADDRESS    (addr[13:0]),
    .MASKWREN   ({wmask[1], wmask[1], wmask[0], wmask[0]}),
    .WREN       (write),
    .CHIPSELECT (cs_1),
    .CLOCK      (clk),
    .STANDBY    (1'b0),
    .SLEEP      (1'b0),
    .POWEROFF   (1'b1),
    .DATAOUT    (rdata_1[15:0])
    );

SB_SPRAM256KA spram1_hi(
    .DATAIN     (wdata[31:16]),
    .ADDRESS    (addr[13:0]),
    .MASKWREN   ({wmask[3], wmask[3], wmask[2], wmask[2]}),
    .WREN       (write),
    .CHIPSELECT (cs_1),
    .CLOCK      (clk),
    .STANDBY    (1'b0),
    .SLEEP      (1'b0),
    .POWEROFF   (1'b1),
    .DATAOUT    (rdata_1[31:16])
    );

endmodule
```

**Comment by igor-m** [comment]
The stack pointers in the original source (with 2 SPRAMs = 16k x 32) are set to 0x7FF0 (the top of spram is 0xFFFF however).
I think the stack should be set to 0xFFF0 in the original source.

With the stack set to 0xFFF0 and for example with this loop with 4 SPRAMs (32k x 32, the code is ~8k words long thus it fits in the lower half):

```
  uint32_t *p = 0;                              // pointer to 32bit unsigned
    for (i=0x0; i<0x8000; i++) {         // spram read loop - we try to read all 128kB = 0x8000 words = 0x20000 bytes
            datas = p[i];   // or *p++
            dataf = 0xdeadbeaf;
            printf_("Address = 0x%0.8x  F = 0x%0.8x  S = 0x%0.8x  \n", i, dataf, datas);
    }
```
    
I am getting this crash when passing the 0x3FFF boundary (we go from spram_0 to spram_1 block)
```
Address = 0x00003ffb  F = 0xdeadbeaf  S = 0x00000000
Address = 0x00003ffc  F = 0xdeadbeaf  S = 0xcfa76b7d
Address = 0x00003ffd  F = 0xdeadbeaf  S = 0xa1137434
Address = 0x00003ffe  F = 0xdeadbeaf  S = 0xf74fe373
Address = 0x00003fff  F = 0xdeadbeaf  S = 0xdd86c956   <<<< the last word in spram_0 block
Address = 0x0000fef8  F = 0xdeadbeaf  S = 0x00040593   <<<< the crash, it should continue up to 0x7FFF (=32k words)
Address = 0x0000fef8  F = 0xdeadbeaf  S = 0x00040593
Address = 0x0000fef8  F = 0xdeadbeaf  S = 0x00040593
Address = 0x0000fef8  F = 0x00000000  S = 0x00040593
Address = 0x0000fef8  F = 0xdeadbeaf  S = 0x00040593
Address = 0x0000fef8  F = 0xdeadbeaf  S = 0x00040593
Address = 0x0000fef8  F = 0xdeadbeaf  S = 0x00040593
Address = 0x0000fef8  F = 0xdeadbeaf  S = 0x00040593
```

With

```
  uint32_t *p = 0;                              // pointer to 32bit unsigned
    for (i=0x0; i<0x8000; i++) {         // psram read loop - we try to read all 128kB = 0x8000 words = 0x20000 bytes
            datas = 0x12345678;   // p[i];
            dataf = 0xdeadbeaf;
            printf_("Address = 0x%0.8x  F = 0x%0.8x  S = 0x%0.8x  \n", i, dataf, datas);
    }
```

```
Address = 0x00003ffc  F = 0xdeadbeaf  S = 0x12345678
Address = 0x00003ffd  F = 0xdeadbeaf  S = 0x12345678
Address = 0x00003ffe  F = 0xdeadbeaf  S = 0x12345678
Address = 0x00003fff  F = 0xdeadbeaf  S = 0x12345678
Address = 0x00004000  F = 0xdeadbeaf  S = 0x12345678
Address = 0x00004001  F = 0xdeadbeaf  S = 0x12345678
```

**Comment by bobbl** [comment]
The problem is, that `rdata` is valid one cycle after `addr` was set. Therefore the selector for `rdata` must be registered. Something like that:

    assign cs_0  =  addr[14];
    assign cs_1  = !addr[14];
    reg q_cs_0;
    always @(posedge clk) begin
        q_c0 <= cs_0;
    end
    assign rdata =  q_cs_0 ? rdata_0 : rdata_1;

However, I am not sure, if `.CHIPSELECT` also disables the read result of the previous memory access. I think using `.WREN` is the safer way to do it.

Looking into `up5k.v` a similar mechanism is used for arbitration between main memory (SPRAM) and boot memory (BRAM). I would leave `SPRAMMemory` untouched at 64K and use two of them:

    wire        mem_valid;
    wire        mem_write;
    wire        mem_write_main0 = mem_write & ~mem_addr[17] & ~mem_addr[16];
    wire        mem_write_main1 = mem_write & ~mem_addr[17] & mem_addr[16];
    wire        mem_write_boot = mem_write & mem_addr[17];
    wire  [3:0] mem_wmask;
    wire [31:0] mem_wdata;
    wire        mem_wgrubby;
    wire [31:0] mem_addr;
    wire [31:0] mem_rdata_main0;
    wire [31:0] mem_rdata_main1;
    wire [31:0] mem_rdata_boot;
    wire [31:0] mem_rdata = q_SelBootMem
        ? mem_rdata_boot
        : (q_SelWhichMainMem ? mem_rdata_main1 
                             : mem_rdata_main0);

    reg q_SelBootMem;
    reg q_SelWhichMainMem;
    always @(posedge clk) begin
        q_SelBootMem <= rstn ? mem_addr[17] : 0;
        q_SelWhichMainMem <= mem_addr[16];
    end

    SPRAMMemory mainmem0 (
        .clk    (clk),
        .write  (mem_write_main0),
        .wmask  (mem_wmask),
        .wdata  (mem_wdata),
        .addr   (mem_addr[15:2]),
        .rdata  (mem_rdata_main0)
    );

    SPRAMMemory mainmem1 (
        .clk    (clk),
        .write  (mem_write_main1),
        .wmask  (mem_wmask),
        .wdata  (mem_wdata),
        .addr   (mem_addr[15:2]),
        .rdata  (mem_rdata_main1)
    );

**Comment by bobbl** [comment]
> The stack pointers in the original source (with 2 SPRAMs = 16k x 32) are set to 0x7FF0 (the top of spram is 0xFFFF however).
I think the stack should be set to 0xFFF0 in the original source

The examples should work on all platforms and the Microsemi FPGA offers only 56KiByte. So 0xDFF0 would be possible, but 0x7FF0 is sufficient for CoreMark and Dhrystone.

**Comment by igor-m** [comment]
Stack pointer: Sure, the 0x1_FFF0 with 128kB spram for the ice40UP5k fpga only.. 

IT WORKS!! (with your changes above - the 2 mainmem modules)

```
    for (i=0x3f00; i<0x4100; i++) {        
             p[i] = (uint32_t)i;
    }

    for (i=0x3f00; i<0x4100; i++) {
             datas = p[i]; 
             dataf = 0xdeadbeaf;
             printf("Address = 0x%08x  F = 0x%08x  S = 0x%08x  \n", i, dataf, datas);
    }

Address = 0x00003ffa  F = 0xdeadbeaf  S = 0x00003ffa                            
Address = 0x00003ffb  F = 0xdeadbeaf  S = 0x00003ffb                            
Address = 0x00003ffc  F = 0xdeadbeaf  S = 0x00003ffc                            
Address = 0x00003ffd  F = 0xdeadbeaf  S = 0x00003ffd                            
Address = 0x00003ffe  F = 0xdeadbeaf  S = 0x00003ffe                            
Address = 0x00003fff  F = 0xdeadbeaf  S = 0x00003fff                            
Address = 0x00004000  F = 0xdeadbeaf  S = 0x00004000                            
Address = 0x00004001  F = 0xdeadbeaf  S = 0x00004001                            
Address = 0x00004002  F = 0xdeadbeaf  S = 0x00004002                            
Address = 0x00004003  F = 0xdeadbeaf  S = 0x00004003                            
Address = 0x00004004  F = 0xdeadbeaf  S = 0x00004004
```

**Comment by igor-m** [comment]
The full 4 SPRAM modules (128kB = 32k words) work with my 125kB large C test binary.
